// tailwind.config.js
module.exports = {
  future: {},
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  important: true,
  theme: {
    fontFamily: {
      sans: [
        `Mona Sans`,
        `-apple-system`,
        `system-ui`,
        `BlinkMacSystemFont`,
        `Segoe UI`,
        `Roboto`,
        `Helvetica Neue`,
        `Arial`,
        `sans-serif`,
      ],
      mono: [
        `Space Mono`,
        `ui-monospace`,
        `SFMono-Regular`,
        `Menlo`,
        `Monaco`,
        `Consolas`,
        `Liberation Mono`,
        `Courier New`,
        `monospace`,
      ],
      script: [`Shantell Sans`, `Space Mono`, `Courier New`, `monospace`],
    },
    fontSize: {
      xs: [`.8rem`, `1.4`],
      sm: [`1rem`, `1.4`],
      base: [`1.25rem`, `1.5`],
      lg: [`1.363rem`, `1.4`],
      xl: [`1.663rem`, `1.4`],
      "2xl": [`1.953rem`, `1.4`],
      "3xl": [`2.441rem`, `1.4`],
      "4xl": [`2.752rem`, `1.4`],
      "5xl": [`3.815rem`, `1.2`],
      "6xl": [`4.168rem`, `1.2`],
      "7xl": [`4.5rem`, `1.2`],
      "8xl": [`5.65rem`, `1.2`],
      "9xl": [`6.75rem`, `1.2`],
      "10xl": [`7.5rem`, `1.2`],
    },
    extend: {
      aspectRatio: {
        sd: `4 / 3`,
      },
      colors: {
        "violet-blue": `#621EF3`,
        pink: `#FD2D78`,
        green: `#E9EF31`,
        aqua: `#3CFFD0`,
        blue: `#00FFEE`,
        orange: `#e05915`,
      },
    },
  },
  variants: {},
  plugins: [],
}